### ISSUE TITLE
How can you embed external markdown?

### ISSUE THREAD

**Issue by ShovanSargunam** [makotokw/wp-gfm#7]
Hi

Is there a way you can embed external markdown inside the page? 
eg: https://raw.githubusercontent.com/makotokw/wp-gfm/master/README.md

Thanks

**Comment by makotokw** [comment]
No way...

But I think it's useful function. I will consider it.

**Comment by ShovanSargunam** [comment]
I tried with this code and it worked :) Would be great if it can be integrated properly as wordpress plugin. 
https://github.com/zmckinnon/jquery-gh-readme

**Comment by makotokw** [comment]
Version 0.8 supported.

```
[embed_markdown url="https://raw.githubusercontent.com/makotokw/wp-gfm/master/README.md"]
```
